src/__init__.py
from flask import Flask,render_template
from flask_cors import CORS
from .utils.extensions import db,ma
from .routes.UserRoute import user_router
from .routes.IndexRoute import index_router

def configure_app():
    app=Flask(__name__)
    CORS(app)
    app.config["SQLALCHEMY_DATABASE_URI"]="mysql+pymysql://root:1234@localhost/users_crud"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"]=False
    app.secret_key="1234"

    db.init_app(app)
    ma.init_app(app)

    with app.app_context():
        db.create_all()

    app.register_blueprint(user_router)
    app.register_blueprint(index_router)
    return app

src/routes/IndexRoute.py
from flask import Blueprint,render_template,request,redirect,url_for,flash
from ..models.entities.User import User,user_schema
from werkzeug.security import generate_password_hash,check_password_hash
from ..utils.extensions import db

index_router=Blueprint('index_router',__name__)

@index_router.route("/")
def index():
    return redirect(url_for("index_router.login"))


@index_router.route("/login",methods=["GET","POST"])
def login():
    if request.method=="POST":
        email=request.form["email"]
        password=request.form["password"]
        user_exist=User.query.filter_by(email=email).first()
        if user_exist != None:
            user_dict=user_schema.dump(user_exist)
            password_user=user_dict["password"]
            if check_password_hash(password_user,password) == True:
                return redirect(url_for("index_router.home"))
            else:
                flash("Contraseña incorrecta")
                return render_template("login.html")
        else:
            flash("Usuario No encontrado")
            return render_template("login.html")

    return render_template("login.html")
    
@index_router.route("/signup",methods=["GET","POST"])
def signup():
    if request.method=="POST":
        dni_ingresado=request.form["dni"]
        usuario_dni=User.query.filter_by(dni=dni_ingresado).first()
        if usuario_dni == None:
            email_ingresado=request.form["email"]
            usuario_email=User.query.filter_by(email=email_ingresado).first()
            if usuario_email == None:
                if request.form["password"] == request.form["check_password"]:
                    password_to_encrypt=generate_password_hash(request.form["password"])
                    user_to_add=User(dni=request.form["dni"],name=request.form["name"],surname=request.form["surname"],password=password_to_encrypt,email=request.form["email"])
                    db.session.add(user_to_add)
                    db.session.commit()
                    return redirect(url_for("index_router.login"))
                else:
                    flash("Las constraseñas no coinciden")
                    return render_template("registrarse.html")
            else:
                flash("El email ya se encuentra registrado")
                return render_template("registrarse.html")
        else:
            flash("DNI ya registrado")
            return render_template("registrarse.html")
    return render_template("registrarse.html")

@index_router.route("/home")
def home():
    return render_template("home.html")

src/routes/UserRoute.py
from flask import Blueprint,jsonify,request
from ..models.entities.User import User,user_schema,users_schema
from ..utils.extensions import db
from werkzeug.security import generate_password_hash

user_router=Blueprint("user_router",__name__)

@user_router.route("/user",methods=['GET'])
def get_users():
    users=User.query.all()
    results=users_schema.dump(users)
    return jsonify(results)

src/templates/home.html
{% extends "./model.html" %}

{% block body %}
<h1>Seccion del home</h1>

{% endblock %}

src/templates/login.html
{% extends "./model.html" %}

{% block body %}
<section class="d-flex flex-column justify-content-center align-items-center h-100" id="form-signin">
  <h1 class="mb-5">Iniciar Sesion</h1>
  {% with messages = get_flashed_messages() %}
   {% if messages %}
      {% for message in messages %}
      <div class="alert alert-danger alert-dismissible" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
   {% endif %}
  {% endwith %}
<form class="gap-4 d-flex flex-column w-50" name="login" action="/login" method="POST">
  <div>
    <label class="form-label">Correo Electronico</label>
    <input type="text" class="form-control" name="email">
  </div>
  <div>
    <label class="form-label">Contraseña</label>
    <input type="text" class="form-control" type="password" name="password">
  </div>
  <button class="btn btn-primary" type="submit"> Iniciar Sesion</button>
</form>
<div class="mt-5">
  <p>No tienes una cuenta? <a class="fw-bolder btn-login" href="{{url_for("index_router.signup")}}" >Registrarse</a></p>
</div>
</section>

{% endblock %}

src/templates/model.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for( "static",filename="css/styles.css" ) }}">
    <title>Documento</title>
</head>

<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/registrarse.html
{% extends "./model.html" %}

{% block body %}
<section class="d-flex flex-column justify-content-center align-items-center h-100" id="form-signin">
  <h1 class="mb-5">Registrarse</h1>
  {% with messages= get_flashed_messages() %}
   {% if messages %}
      {% for message in messages %}
      <div class="alert alert-danger alert-dismissible" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
   {% endif %}
  {% endwith %}
<form class="gap-4 d-flex flex-column w-50" name="login" action="/signup" method="POST">
    <div class="row">
  <div class="col-6">
    <label class="form-label">Nombre</label>
    <input type="text" class="form-control" name="name">
  </div>
  <div class="col-6">
    <label class="form-label">Apellido</label>
    <input type="text" class="form-control" name="surname">
  </div>
  <div>
    <label class="form-label">DNI</label>
    <input type="number" class="form-control" name="dni">
  </div>
  <div>
    <label class="form-label">Correo Electronico</label>
    <input type="text" class="form-control" name="email">
  </div>
  <div>
    <label class="form-label">Contraseña</label>
    <input type="text" class="form-control" type="password" name="password">
  </div>
  <div>
    <label class="form-label">Repetir Contraseña</label>
    <input type="text" class="form-control" type="password" name="check_password">
  </div>
</div>
  <button class="btn btn-primary" type="submit">Registrarse</button>
</form>
<div class="mt-5">
  <p>Ya tienes una cuenta? <a class="fw-bolder btn-login" href="{{url_for("index_router.login")}}" >Inicia Sesion</a></p>
</div>
</section>

{% endblock %}